### ISSUE TITLE
画像最適化について

### ISSUE THREAD

**Issue by eteeeeeerminal** [VirtualProgrammersNetwork/vpn-website#14]
Webサイトで画像を表示するにあたって、軽量化のために、よしなに解像度や形式を変換してくれるライブラリが存在する。

Next.jsの標準機能にも画像最適化の機能があるが、これは、画像を表示する際に表示側に応じて動的に画像を最適化して返す機能である。
つまり、読み込み時に稼働するので、純粋な静的サイトでは採用できない。(GitHub pagesにホストする前提なので、静的サイトしか使えない)
https://nextjs.org/docs/basic-features/image-optimization

以下では、Next.jsで画像最適化を行う方法について調べた内容をまとめる。
GitHub pagesで済むように、静的サイト生成をする前提で考える。

一通り調べた結果、手元の環境で動かせなかったので、暫定的に、画像の最適化をしない実装でいこうと思う。
変更しやすいように画像を表示する用にコンポーネントを切り出す。

**Comment by eteeeeeerminal** [comment]
# 公式の画像最適化は純粋な静的サイトでは使えない
公式のImage componentを使用した状態で、`next export`をすると、以下のようなエラーが出る。
これは、標準で画像の最適化は動的に行われると言ってる。`next start`でAPIを立ち上げるか、Vercelを使うか、他の画像最適化ツールを使えと言ってる。
ホスティング先をGitHub pagesにしている限り、公式のImage componentは使えない。
Vercelにホスティングすると、アカウント管理が面倒になるかもしれない。少なくとも、ホスティング方法について話し合いが必要。

```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /mnt/d/Github/vpn/vpn-website/node_modules/next/dist/export/index.js:14:785
    at async Span.traceAsyncFn (/mnt/d/Github/vpn/vpn-website/node_modules/next/dist/telemetry/trace/trace.js:6:584)
```

**Comment by eteeeeeerminal** [comment]
# 静的サイトだけで乗り切るために、ビルド時に画像を最適化する方法を模索
[next-optimized-images](https://github.com/cyrilwanner/next-optimized-images)というパッケージを使うとできるらしい。
これは、他の色んな画像最適化系のパッケージをラップしてよしなにしてくれるもの。
`next-optimized-images`は現行のバージョン2と、ベータのバージョン3が存在する。

両方試してみたが、画像がうまく読み込めなかった。エラー等は出ていないものの、画像が表示されず、画像がないことを示すマークが表示された。
実際に動いている例もあるが、なぜか動かなかった。時間をあけてトライすれば案外動くかも知れない。
しかし、そもそも`next-optimized-images`自体、最後のコミットが半年以上前なので、本格採用はしたくない。

試すときに参考にした記事を列挙しておく
- v2 
  - `next-optimized-images`の使い方が分かりやすく書いてる https://qiita.com/github0013@github/items/8d1dfa25374e77861156
  - 遅延ロードもやってる記事、デモサイトとコードもあり https://zenn.dev/itomise/articles/20356a794b665f
- v3 https://github.com/cyrilwanner/next-optimized-images/tree/canary
  - `next-optimized-images`と書いてあるが、`react-optimized-image`っぽい

**Comment by eteeeeeerminal** [comment]
# 画像最適化はせず、画像用のコンポーネントを切り出すことで暫定的に対処
画像最適化でうまい方法が分からなかったので、今後導入しやすいように、コンポーネントの切り出しだけ行った。
純粋な静的サイトを諦めるにしても、ビルド時に最適化するにしても、未来の自分に決めてもらおう。お祈り。

**Comment by eteeeeeerminal** [comment]
[next-img](https://github.com/humaans/next-img)なるパッケージを見つけるも、typescriptに対応していない模様。
```
Could not find a declaration file for module 'next-img'. 'D:/Github/vpn/vpn-website/node_modules/next-img/dist/react-components/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/next-img` if it exists or add a new declaration (.d.ts) file containing `declare module 'next-img';`ts(7016)
```
